name: genai issue validator w/ azure
on:
  issues:
    types: [opened, edited]
concurrency:
  group: issues-${{ github.event.issue.number }}-az
  cancel-in-progress: true
env:
  GENAISCRIPT_DEFAULT_MODEL: azure:gpt-4o-mini
  GENAISCRIPT_DEFAULT_SMALL_MODEL: azure:gpt-4o-mini
  GENAISCRIPT_DEFAULT_VISION_MODEL: azure:gpt-4o-mini
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - run: npm ci
    - name: genaiscript issue-review
      run: npx -y genaiscript run validate-issue -prc --out-trace $GITHUB_STEP_SUMMARY
      env:
        GITHUB_ISSUE: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AZURE_OPENAI_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
